queue:
    branch:         BranchModule
    clean:          CleanModule
    bump_version:   BumpVersionModule
    build:          BuildModule
    tests:          TestsModule
    pack_ipa:       PackIpaModule
    sign_ipa:       SignIpaModule
    pack_dsym:      PackDsymModule
    upload_doa:     UploadDoaModule


default: &default
    sdk:            iphoneos
    configuration:  AdHoc