source  "https://rubygems.org"

gem "rest-client", "~> 1.6.7"
gem "json", "~> 1.7.6"
gem "hashr", "~> 0.0.22"
gem "ocunit2junit"
gem "commander"
gem "xcodeproj", "~> 0.9.0"
gem "plist", "~> 3.1.0"
gem "rmagick", "~> 2.13.2"
